! (function (wndw) {
var jadify = function (jade) {
return function anonymous(locals) {
var buf = [];
buf.push("<div class=\"container\"><div class=\"pure-u-1\"><div class=\"tmpst-footer-primary pure-u-5-12\"><p>Simple Introduction</p><p class=\"Tmpst-footer-copyright\">© 2014 Tmpst Inc. All Rights Reserved.</p></div><div class=\"pure-u-7-12\"><div class=\"pure-u-1\"><div class=\"tmpst-footer-column pure-u-1-4\"><h6>Company</h6><a href=\"/dashboard\" class=\"tmpst-footer-link internal-home\">Dashboard</a><a href=\"/vms\" class=\"tmpst-footer-link internal-home\">VMS</a><a href=\"/services/create\" class=\"tmpst-footer-link internal-home\">Create DB</a><a href=\"/services/list\" class=\"tmpst-footer-link internal-home\">DATABASES</a></div><div class=\"tmpst-footer-column pure-u-1-4\"><h6>Company</h6><a href=\"/dashboard\" class=\"tmpst-footer-link internal-home\">Dashboard</a><a href=\"/vms\" class=\"tmpst-footer-link internal-home\">VMS</a><a href=\"/services/create\" class=\"tmpst-footer-link internal-home\">Create DB</a><a href=\"/services/list\" class=\"tmpst-footer-link internal-home\">DATABASES</a></div><div class=\"tmpst-footer-column pure-u-1-4\"><h6>Company</h6><a href=\"/dashboard\" class=\"tmpst-footer-link internal-home\">Dashboard</a><a href=\"/vms\" class=\"tmpst-footer-link internal-home\">VMS</a><a href=\"/services/create\" class=\"tmpst-footer-link internal-home\">Create DB</a><a href=\"/services/list\" class=\"tmpst-footer-link internal-home\">DATABASES</a></div><div class=\"tmpst-footer-column pure-u-1-4\"><h6>Company</h6><a href=\"/dashboard\" class=\"tmpst-footer-link internal-home\">Dashboard</a><a href=\"/vms\" class=\"tmpst-footer-link internal-home\">VMS</a><a href=\"/services/create\" class=\"tmpst-footer-link internal-home\">Create DB</a><a href=\"/services/list\" class=\"tmpst-footer-link internal-home\">DATABASES</a></div></div></div></div></div>");;return buf.join("");
}
};
"function" == typeof define && define.amd ? define("pages/home/template/footer.html", ["js/lib/jade"], function (e) {
return jadify(e); 
}) : wndw.jade.templates["pages/home/template/footer"]= jadify(wndw.jade.helpers);
}(window));