(function (wndw) {
var jadify = function (jade) {
return function anonymous(locals) {
var buf = [];
buf.push("<div class=\"container\"><div data-js-ui-tabs=\"data-js-ui-tabs\" class=\"tabs mt20\"></div><div class=\"pure-u-1 services\"><h3 class=\"label\">CREATE A DATABASE</h3><table class=\"table pure-table pure-table-horizontal\"><tbody><tr><td>TYPE</td><td><select class=\"select\"><option>MySQL 5.6</option><option>MS SQL 2012</option></select></td></tr><tr><td>SIZE</td><td><select class=\"select\"><option>Basic: Dedicate server, shared VM, 256MB memory, 2560MB storage, 30 connections</option></select></td></tr><tr><td>DB ALIAS</td><td><div class=\"input-combobox layer-trigger\"><input placeholder=\"DB ALIAS\" maxlength=\"32\" class=\"text ellipsis\"/></div></td></tr><tr><td>LOGIN PASSWORD</td><td><div class=\"input-combobox layer-trigger\"><input placeholder=\"password\" maxlength=\"32\" class=\"text ellipsis\"/></div></td></tr><tr><td>CONFIRM PASSWORD</td><td><div class=\"input-combobox layer-trigger\"><input placeholder=\"confirm password\" maxlength=\"32\" class=\"text ellipsis\"/></div></td></tr><tr><td></td><td><a class=\"pure-button pure-button-active\"><i class=\"fa fa-plus\"> </i>CREATE</a></td></tr></tbody></table><h3 class=\"label\">MY DATABASES</h3><table class=\"table pure-table pure-table-horizontal\"><thead><th class=\"checkbox-column\"><input type=\"checkbox\"/></th><th class=\"number-column\"></th><th>DB</th><th>Version</th><th>Plan</th><th>Created</th><th align=\"center\" width=\"350px\">Operations</th></thead><tbody><td class=\"checkbox-column\"><input type=\"checkbox\"/></td><td class=\"number-column\">1</td><td title=\"\"><div class=\"ellipsis item-content\">Steve's DB</div></td><td title=\"\"><div class=\"ellipsis item-content\">MSSQL 2012</div></td><td title=\"\"><div class=\"ellipsis item-content\">Basic</div></td><td title=\"\"><div class=\"ellipsis item-content\">2/18/2014</div></td><td align=\"center\" class=\"operation-column\"><a class=\"button pure-button\">BACKUP</a><a class=\"button pure-button\">DELETE</a><a class=\"button pure-button\">CHANGE PASSWORD</a></td></tbody></table></div></div>");;return buf.join("");
}
};
"function" == typeof define && define.amd ? define("pages/home/services/servicesBody.html", ["js/lib/jade"], function (e) {
return jadify(e); 
}) : wndw.jade.templates.servicesBody= jadify(wndw.jade.helpers);
}(window));