! (function (wndw) {
var jadify = function (jade) {
return function anonymous(locals) {
var buf = [];
buf.push("<div class=\"container\"><div class=\"pure-u-1 tmpst-full-canvas\"><div data-js-ui-tabs=\"data-js-ui-tabs\" class=\"tabs mt20\"></div><div><h3 data-section=\"create\" class=\"label\">CREATE A DATABASE</h3><form id=\"instance-form\" class=\"pure-form pure-form-aligned\"><fieldset><div class=\"pure-control-group\"><label for=\"type\">TYPE</label><select name=\"type\" id=\"type\" class=\"pure-input-2-3\"><option>MySQL 5.6</option><option>MSSQL 2012</option></select></div><div class=\"pure-control-group\"><label for=\"DESCRIPTION\">DESCRIPTION</label><select name=\"description\" id=\"description\" class=\"pure-input-2-3\"><option>Basic: Dedicate server, shared VM, 256MB memory, 2560MB storage, 30 connections</option></select></div><div class=\"pure-control-group\"><label for=\"database\">DB</label><input type=\"text\" placeholder=\"DB\" name=\"database\" id=\"database\" class=\"pure-input-1-3\"/></div><div class=\"pure-control-group\"><label for=\"password\">LOGIN PASSWORD</label><input type=\"password\" placeholder=\"LOGIN PASSWORD\" name=\"password\" id=\"password\" class=\"pure-input-1-3\"/></div><div class=\"pure-control-group\"><label for=\"password-repeat\">CONFIRM PASSWORD</label><input type=\"password\" placeholder=\"CONFIRM PASSWORD\" name=\"password-repeat\" id=\"password-repeat\" class=\"pure-input-1-3\"/></div><div class=\"pure-control-group\"><label></label><a class=\"pure-button pure-button-active create-instance\"><i class=\"fa fa-plus\"> </i>CREATE</a></div><div class=\"validation-error\"></div></fieldset></form><h3 data-section=\"list\" class=\"label\">MY DATABASES</h3><div id=\"instances-container\" class=\"instances-container\"><div class=\"header-group\"><div class=\"row head-row\"><div class=\"cell number-cell\"></div><div class=\"cell\">DB</div><div class=\"cell\">TYPE</div><div class=\"cell\">PASSWORD</div></div></div><div class=\"row-group\"></div></div></div></div></div>");;return buf.join("");
}
};
"function" == typeof define && define.amd ? define("pages/home/services/servicesBody.html", ["js/lib/jade"], function (e) {
return jadify(e); 
}) : wndw.jade.templates["pages/home/services/servicesBody"]= jadify(wndw.jade.helpers);
}(window));